use UNIVER;

/* ex1 */
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('евшв')
GROUP BY ROLLUP( GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY );

/* ex2 */
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('евшв')
GROUP BY CUBE( GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY );

/* ex3 */
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('евшв')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
UNION
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('Ш д')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY ;

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('евшв')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
UNION ALL
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('Ш д')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY ;

/* ex4 */
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('евшв')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
INTERSECT
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('Ш д')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY

/* ex5 */
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('евшв')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY
EXCEPT
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY, AVG(PROGRESS.NOTE) [MARK]
from GROUPS, PROGRESS, FACULTY, STUDENT
where GROUPS.FACULTY = FACULTY.FACULTY and
FACULTY.FACULTY in ('Ш д')
GROUP BY GROUPS.PROFESSION, PROGRESS.SUBJECT, GROUPS.FACULTY